//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuzzleTimer.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PuzzleTimer.Languages.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About application.
        /// </summary>
        internal static string AboutAuthor {
            get {
                return ResourceManager.GetString("AboutAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AboutAuthorText {
            get {
                return ResourceManager.GetString("AboutAuthorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string AboutText1 {
            get {
                return ResourceManager.GetString("AboutText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Dmytro Alyanakh.
        /// </summary>
        internal static string AboutText2 {
            get {
                return ResourceManager.GetString("AboutText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information look on.
        /// </summary>
        internal static string AboutText3 {
            get {
                return ResourceManager.GetString("AboutText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avarage.
        /// </summary>
        internal static string Avg {
            get {
                return ResourceManager.GetString("Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avarage 3 last: .
        /// </summary>
        internal static string Avg3Last {
            get {
                return ResourceManager.GetString("Avg3Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avarage 5 last: .
        /// </summary>
        internal static string Avg5Last {
            get {
                return ResourceManager.GetString("Avg5Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avarage all: .
        /// </summary>
        internal static string AvgAll {
            get {
                return ResourceManager.GetString("AvgAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected:.
        /// </summary>
        internal static string AvgAnySelected {
            get {
                return ResourceManager.GetString("AvgAnySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        internal static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string ChartWindowText {
            get {
                return ResourceManager.GetString("ChartWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all.
        /// </summary>
        internal static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        internal static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        internal static string CultureString {
            get {
                return ResourceManager.GetString("CultureString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CustomScrambleWindowButtonCancel {
            get {
                return ResourceManager.GetString("CustomScrambleWindowButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string CustomScrambleWindowButtonDone {
            get {
                return ResourceManager.GetString("CustomScrambleWindowButtonDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter custom scramble.
        /// </summary>
        internal static string CustomScrambleWindowText {
            get {
                return ResourceManager.GetString("CustomScrambleWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month/day/year hour:minute:second.
        /// </summary>
        internal static string DateToolTipText {
            get {
                return ResourceManager.GetString("DateToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating....
        /// </summary>
        internal static string Generating {
            get {
                return ResourceManager.GetString("Generating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string GridHeaderIdText {
            get {
                return ResourceManager.GetString("GridHeaderIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puzzle type.
        /// </summary>
        internal static string GridHeaderPuzzleNameText {
            get {
                return ResourceManager.GetString("GridHeaderPuzzleNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scramble.
        /// </summary>
        internal static string GridHeaderScrambleText {
            get {
                return ResourceManager.GetString("GridHeaderScrambleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution date.
        /// </summary>
        internal static string GridHeaderSolutionDateText {
            get {
                return ResourceManager.GetString("GridHeaderSolutionDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution time.
        /// </summary>
        internal static string GridHeaderSolutionTimeText {
            get {
                return ResourceManager.GetString("GridHeaderSolutionTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick guide:.
        /// </summary>
        internal static string HelpText1 {
            get {
                return ResourceManager.GetString("HelpText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9. To show avarage solution time on custom number of items input appropriet number in the bottom of the window or select items(lines) for those it is need to find avarage solution time and it will show in the bottom of the window;.
        /// </summary>
        internal static string HelpText10 {
            get {
                return ResourceManager.GetString("HelpText10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10. You can change your current puzzle in combo box in the bottom of the screen;.
        /// </summary>
        internal static string HelpText11 {
            get {
                return ResourceManager.GetString("HelpText11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11. On main window button New scramble generates new scramble. Button Table/Unfold shows table/unfold accordingly;.
        /// </summary>
        internal static string HelpText12 {
            get {
                return ResourceManager.GetString("HelpText12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.To start timer press Space button for more then 1 second and then unpress, to stop press Space button again;.
        /// </summary>
        internal static string HelpText2 {
            get {
                return ResourceManager.GetString("HelpText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.To use scrambles for 2x2-7x7 you must hold your cube this way: Front - Green, Left - Orange;For Skewb: Up - White, Left - Green; For Pyraminx: Front - Green, Left - Red; For Megaminx: Up - White, Front - Dark Green;.
        /// </summary>
        internal static string HelpText3 {
            get {
                return ResourceManager.GetString("HelpText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.Double-click row to enter update menu or select row and click Edit-&gt;Update;.
        /// </summary>
        internal static string HelpText4 {
            get {
                return ResourceManager.GetString("HelpText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.Click on pencil on the main screen to input custom scramble;.
        /// </summary>
        internal static string HelpText5 {
            get {
                return ResourceManager.GetString("HelpText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. In menu item Help-&gt;Settings you can change theme and language of the application;.
        /// </summary>
        internal static string HelpText6 {
            get {
                return ResourceManager.GetString("HelpText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. In Edit menu item you can Add, Clear all items; Update and Delete (also by clicking delete button after selection of line or lines) item if appropriate line was selected in table. Also you can copy main information about solution to share if appropriate line was selected in table..
        /// </summary>
        internal static string HelpText7 {
            get {
                return ResourceManager.GetString("HelpText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. To see chart on current puzzle click on menu item Chart;.
        /// </summary>
        internal static string HelpText8 {
            get {
                return ResourceManager.GetString("HelpText8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8. If you want to hide stopwatch while solving puzzle uncheck &quot;Show time&quot; checkbox;.
        /// </summary>
        internal static string HelpText9 {
            get {
                return ResourceManager.GetString("HelpText9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INCORRECT SOLUTION DATE.
        /// </summary>
        internal static string incorrectDate {
            get {
                return ResourceManager.GetString("incorrectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INCORRECT SCRAMBLE.
        /// </summary>
        internal static string incorrectScramble {
            get {
                return ResourceManager.GetString("incorrectScramble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , SCRAMBLE.
        /// </summary>
        internal static string incorrectScramblePlus {
            get {
                return ResourceManager.GetString("incorrectScramblePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INCORRECT SOLUTION TIME.
        /// </summary>
        internal static string incorrectTime {
            get {
                return ResourceManager.GetString("incorrectTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , SOLUTION TIME.
        /// </summary>
        internal static string incorrectTimePlus {
            get {
                return ResourceManager.GetString("incorrectTimePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last:.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Scramble.
        /// </summary>
        internal static string NewScramble {
            get {
                return ResourceManager.GetString("NewScramble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available!.
        /// </summary>
        internal static string NewVersionAvailableText {
            get {
                return ResourceManager.GetString("NewVersionAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version of program.
        /// </summary>
        internal static string NewVersionText1 {
            get {
                return ResourceManager.GetString("NewVersionText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to available! Would you like to go to site and download it?.
        /// </summary>
        internal static string NewVersionText2 {
            get {
                return ResourceManager.GetString("NewVersionText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected puzzle:.
        /// </summary>
        internal static string PuzzleType {
            get {
                return ResourceManager.GetString("PuzzleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scramble:.
        /// </summary>
        internal static string Scramble {
            get {
                return ResourceManager.GetString("Scramble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show time.
        /// </summary>
        internal static string ShowTime {
            get {
                return ResourceManager.GetString("ShowTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution date:.
        /// </summary>
        internal static string SolutionDate {
            get {
                return ResourceManager.GetString("SolutionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution time:.
        /// </summary>
        internal static string SolutionTime {
            get {
                return ResourceManager.GetString("SolutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples Hours:Minutes:Seconds.Milliseconds(only first two digits, f.e. if 63 ms then write 0.06, 727 ms then 0.72).
        /// </summary>
        internal static string SolutionTimeTextBoxToolTipText {
            get {
                return ResourceManager.GetString("SolutionTimeTextBoxToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfold.
        /// </summary>
        internal static string Unfold {
            get {
                return ResourceManager.GetString("Unfold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesText {
            get {
                return ResourceManager.GetString("YesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero items! Can&apos;t draw chart!.
        /// </summary>
        internal static string ZeroItemsCantDrawChart {
            get {
                return ResourceManager.GetString("ZeroItemsCantDrawChart", resourceCulture);
            }
        }
    }
}
