//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuzzleTimer.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Russian {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Russian() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PuzzleTimer.Languages.Russian", typeof(Russian).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Про приложение.
        /// </summary>
        internal static string AboutAuthor {
            get {
                return ResourceManager.GetString("AboutAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AboutAuthorText {
            get {
                return ResourceManager.GetString("AboutAuthorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия 1.0.0.
        /// </summary>
        internal static string AboutText1 {
            get {
                return ResourceManager.GetString("AboutText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создано Дмитрием Альянахом.
        /// </summary>
        internal static string AboutText2 {
            get {
                return ResourceManager.GetString("AboutText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Больше информации на.
        /// </summary>
        internal static string AboutText3 {
            get {
                return ResourceManager.GetString("AboutText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Середнее.
        /// </summary>
        internal static string Avg {
            get {
                return ResourceManager.GetString("Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Среднее 3 посл.: .
        /// </summary>
        internal static string Avg3Last {
            get {
                return ResourceManager.GetString("Avg3Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Среднее 5 посл.: .
        /// </summary>
        internal static string Avg5Last {
            get {
                return ResourceManager.GetString("Avg5Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Среднее всех: .
        /// </summary>
        internal static string AvgAll {
            get {
                return ResourceManager.GetString("AvgAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to избранных:.
        /// </summary>
        internal static string AvgAnySelected {
            get {
                return ResourceManager.GetString("AvgAnySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to График.
        /// </summary>
        internal static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время.
        /// </summary>
        internal static string ChartWindowText {
            get {
                return ResourceManager.GetString("ChartWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить всё.
        /// </summary>
        internal static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать в буф. обмена.
        /// </summary>
        internal static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ua-UA.
        /// </summary>
        internal static string CultureString {
            get {
                return ResourceManager.GetString("CultureString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string CustomScrambleWindowButtonCancel {
            get {
                return ResourceManager.GetString("CustomScrambleWindowButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        internal static string CustomScrambleWindowButtonDone {
            get {
                return ResourceManager.GetString("CustomScrambleWindowButtonDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите собственный скрамбл.
        /// </summary>
        internal static string CustomScrambleWindowText {
            get {
                return ResourceManager.GetString("CustomScrambleWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to месяц/день/год час:минута:секунда.
        /// </summary>
        internal static string DateToolTipText {
            get {
                return ResourceManager.GetString("DateToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правка.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Генерирование....
        /// </summary>
        internal static string Generating {
            get {
                return ResourceManager.GetString("Generating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string GridHeaderIdText {
            get {
                return ResourceManager.GetString("GridHeaderIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип головоломки.
        /// </summary>
        internal static string GridHeaderPuzzleNameText {
            get {
                return ResourceManager.GetString("GridHeaderPuzzleNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрамбл.
        /// </summary>
        internal static string GridHeaderScrambleText {
            get {
                return ResourceManager.GetString("GridHeaderScrambleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата сборки.
        /// </summary>
        internal static string GridHeaderSolutionDateText {
            get {
                return ResourceManager.GetString("GridHeaderSolutionDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время сборки.
        /// </summary>
        internal static string GridHeaderSolutionTimeText {
            get {
                return ResourceManager.GetString("GridHeaderSolutionTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощь.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое руководство:.
        /// </summary>
        internal static string HelpText1 {
            get {
                return ResourceManager.GetString("HelpText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9. Чтобы увидеть среднее время сборки любого количества последних записей введите соответвующее число внизу окна или выделите записи для которых нужно найти середнее время сборки и оно появится в нижней части экрана;.
        /// </summary>
        internal static string HelpText10 {
            get {
                return ResourceManager.GetString("HelpText10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10. Изменить головоломку можна в выпадающем меню в нижней части окна;.
        /// </summary>
        internal static string HelpText11 {
            get {
                return ResourceManager.GetString("HelpText11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11. На главном окне кнопка Новый скрамбл генерирует новый скрамбл. Кнопка Таблица/Развертка показывает таблицу/развуртку соответственно;.
        /// </summary>
        internal static string HelpText12 {
            get {
                return ResourceManager.GetString("HelpText12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Чтобы запустить таймер, нажмите кнопку «Пробел» и удерживайте её более 1 секунды, а затем отпустите, для остановки нажмите кнопку «Пробел» ещё раз;.
        /// </summary>
        internal static string HelpText2 {
            get {
                return ResourceManager.GetString("HelpText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Чтобы использовать скрамблы для 2x2-7x7, вы должны держать свой куб так: Перёд - Зелёный, Слева - Оранжевый; Для Skewb: Верх - Белый, Слева - Зелёный; Для Pyraminx: Перёд - Зелёный, Слева - Красное; Для Megaminx: Верх - Белый, Перёд - Темнозелёный;.
        /// </summary>
        internal static string HelpText3 {
            get {
                return ResourceManager.GetString("HelpText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Дважды нажмите на строку в таблице, чтобы войти в меню обновления, или выберите строку и нажмите Правка-&gt; Обновить;.
        /// </summary>
        internal static string HelpText4 {
            get {
                return ResourceManager.GetString("HelpText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Нажмите на карандаш на главном экране, чтобы ввести свой скрамбл;.
        /// </summary>
        internal static string HelpText5 {
            get {
                return ResourceManager.GetString("HelpText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. В пункте меню Помощь-&gt;Настройки можна изменить тему и язык приложения;.
        /// </summary>
        internal static string HelpText6 {
            get {
                return ResourceManager.GetString("HelpText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. В пункте меню Правка можна Добавить записи, Удалить все записи; Обновить или Удалить (также с помощю кнопки delete на клавиатуре после вибора записи или записей) записи, если соответвующая ленейка была выбрана в таблице. Также можна копировать основную информацию про сборку, чтобы поделиться, если соответвующая ленейка была выбрана в таблице;.
        /// </summary>
        internal static string HelpText7 {
            get {
                return ResourceManager.GetString("HelpText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. Чтобы увидеть график по данной головоломке нажмите на пункт меню График;.
        /// </summary>
        internal static string HelpText8 {
            get {
                return ResourceManager.GetString("HelpText8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8. Чтобы не видеть секундомер во время сборки уберите птичку в &quot;Показать время&quot;;.
        /// </summary>
        internal static string HelpText9 {
            get {
                return ResourceManager.GetString("HelpText9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НЕПРАВИЛЬНАЯ ДАТА СБОРКИ.
        /// </summary>
        internal static string incorrectDate {
            get {
                return ResourceManager.GetString("incorrectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НЕПРАВИЛЬНЫЙ СКРАМБЛ.
        /// </summary>
        internal static string incorrectScramble {
            get {
                return ResourceManager.GetString("incorrectScramble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , СКРАМБЛ.
        /// </summary>
        internal static string incorrectScramblePlus {
            get {
                return ResourceManager.GetString("incorrectScramblePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НЕПРАВИЛЬНОЕ ВРЕМЯ СБОРКИ.
        /// </summary>
        internal static string incorrectTime {
            get {
                return ResourceManager.GetString("incorrectTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , ВРЕМЯ СБОРКИ.
        /// </summary>
        internal static string incorrectTimePlus {
            get {
                return ResourceManager.GetString("incorrectTimePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык:.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to посл.:.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый скрамбл.
        /// </summary>
        internal static string NewScramble {
            get {
                return ResourceManager.GetString("NewScramble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избранная головоломка:.
        /// </summary>
        internal static string PuzzleType {
            get {
                return ResourceManager.GetString("PuzzleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрамбл:.
        /// </summary>
        internal static string Scramble {
            get {
                return ResourceManager.GetString("Scramble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать время.
        /// </summary>
        internal static string ShowTime {
            get {
                return ResourceManager.GetString("ShowTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата сборки:.
        /// </summary>
        internal static string SolutionDate {
            get {
                return ResourceManager.GetString("SolutionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время сборки:.
        /// </summary>
        internal static string SolutionTime {
            get {
                return ResourceManager.GetString("SolutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пример: часы:минуты:секунды.милисекунды(только первые две цифры, например, если 63 милисекунды, тогда пишите 0.06, 727 милесекунд тогда 0.72).
        /// </summary>
        internal static string SolutionTimeTextBoxToolTipText {
            get {
                return ResourceManager.GetString("SolutionTimeTextBoxToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таблица.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема:.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Развертка.
        /// </summary>
        internal static string Unfold {
            get {
                return ResourceManager.GetString("Unfold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нету записей! Невозможно построить график!.
        /// </summary>
        internal static string ZeroItemsCantDrawChart {
            get {
                return ResourceManager.GetString("ZeroItemsCantDrawChart", resourceCulture);
            }
        }
    }
}
