//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuzzleTimer.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Ukrainian {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ukrainian() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PuzzleTimer.Languages.Ukrainian", typeof(Ukrainian).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Про програму.
        /// </summary>
        internal static string AboutAuthor {
            get {
                return ResourceManager.GetString("AboutAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AboutAuthorText {
            get {
                return ResourceManager.GetString("AboutAuthorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версія 1.0.0.
        /// </summary>
        internal static string AboutText1 {
            get {
                return ResourceManager.GetString("AboutText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створено Дмитром Альянахом.
        /// </summary>
        internal static string AboutText2 {
            get {
                return ResourceManager.GetString("AboutText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Більше інформації на.
        /// </summary>
        internal static string AboutText3 {
            get {
                return ResourceManager.GetString("AboutText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавити.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Середнє.
        /// </summary>
        internal static string Avg {
            get {
                return ResourceManager.GetString("Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Середнє 3 ост.: .
        /// </summary>
        internal static string Avg3Last {
            get {
                return ResourceManager.GetString("Avg3Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Середнє 5 ост.: .
        /// </summary>
        internal static string Avg5Last {
            get {
                return ResourceManager.GetString("Avg5Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Середнє всіх: .
        /// </summary>
        internal static string AvgAll {
            get {
                return ResourceManager.GetString("AvgAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вибраних:.
        /// </summary>
        internal static string AvgAnySelected {
            get {
                return ResourceManager.GetString("AvgAnySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скасувати.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Графік.
        /// </summary>
        internal static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Час.
        /// </summary>
        internal static string ChartWindowText {
            get {
                return ResourceManager.GetString("ChartWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистити все.
        /// </summary>
        internal static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скопіювати в буф. обміну.
        /// </summary>
        internal static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ua-UA.
        /// </summary>
        internal static string CultureString {
            get {
                return ResourceManager.GetString("CultureString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відміна.
        /// </summary>
        internal static string CustomScrambleWindowButtonCancel {
            get {
                return ResourceManager.GetString("CustomScrambleWindowButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        internal static string CustomScrambleWindowButtonDone {
            get {
                return ResourceManager.GetString("CustomScrambleWindowButtonDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть свій скрамбл.
        /// </summary>
        internal static string CustomScrambleWindowText {
            get {
                return ResourceManager.GetString("CustomScrambleWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to місяць/день/рік година:хвилина:секунда.
        /// </summary>
        internal static string DateToolTipText {
            get {
                return ResourceManager.GetString("DateToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Генерування....
        /// </summary>
        internal static string Generating {
            get {
                return ResourceManager.GetString("Generating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string GridHeaderIdText {
            get {
                return ResourceManager.GetString("GridHeaderIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип головоломки.
        /// </summary>
        internal static string GridHeaderPuzzleNameText {
            get {
                return ResourceManager.GetString("GridHeaderPuzzleNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрамбл.
        /// </summary>
        internal static string GridHeaderScrambleText {
            get {
                return ResourceManager.GetString("GridHeaderScrambleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата збірки.
        /// </summary>
        internal static string GridHeaderSolutionDateText {
            get {
                return ResourceManager.GetString("GridHeaderSolutionDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Час збірки.
        /// </summary>
        internal static string GridHeaderSolutionTimeText {
            get {
                return ResourceManager.GetString("GridHeaderSolutionTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допомога.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Короткий посібник:.
        /// </summary>
        internal static string HelpText1 {
            get {
                return ResourceManager.GetString("HelpText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9. Щоб побачити середній час збірки довільної кількості останніх записів введіть відповідне число внизу вікна або виділіть записи для яких потрібно знайти середній час зборки і воно появиться в нижній частині екрану;.
        /// </summary>
        internal static string HelpText10 {
            get {
                return ResourceManager.GetString("HelpText10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10. Змінити головоломку можна в випадаючому меню в нижній частині вікна;.
        /// </summary>
        internal static string HelpText11 {
            get {
                return ResourceManager.GetString("HelpText11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11. На головному вікні кнопка Новий скрамбл генерує новий скрамбл. Кнопка Таблиця/Розгортка показує таблицю/розгортку відповідно;.
        /// </summary>
        internal static string HelpText12 {
            get {
                return ResourceManager.GetString("HelpText12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.Щоб запустити таймер, натисніть кнопку пробілу більше 1 секунди, а потім відпустіть, щоб зупинити, натисніть кнопку пробілу ще раз;.
        /// </summary>
        internal static string HelpText2 {
            get {
                return ResourceManager.GetString("HelpText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.Щоб використовувати скрамбли для 2x2-7x7, ви повинні тримати свій кубик таким чином: Перід - Зелений, Зліва - оранжевий; Для Skewb: Верх - Білий, Зліва - Зелене; Для Pyraminx: Перід - Зелений, Зліва - Червоне; Для Megaminx: Верх - Білий, Перід - Темнозелений;.
        /// </summary>
        internal static string HelpText3 {
            get {
                return ResourceManager.GetString("HelpText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Двічі натисніть на рядок в таблиці, щоб увійти в меню оновлення, або виберіть рядок і натисніть Редагувати-&gt; Оновити;.
        /// </summary>
        internal static string HelpText4 {
            get {
                return ResourceManager.GetString("HelpText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Натисніть на олівець на головному екрані, щоб ввести свій скрамбл;.
        /// </summary>
        internal static string HelpText5 {
            get {
                return ResourceManager.GetString("HelpText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. В пункті меню Допомога-&gt;Налаштування можна зміни тему і мову програми;.
        /// </summary>
        internal static string HelpText6 {
            get {
                return ResourceManager.GetString("HelpText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. В пункті меню Редагувати можна Добавити записи, Видалити всі записи; Оновити або Видалити (також за допомогою кнопки delete на клавіатурі після вибору запису або записів)  записи, якщо відповідна лінійка була вибрана в таблиці. Також можна копіювати основну інформацію про збірку, щоб поділитися,  якщо відповідна лінійка була вибрана в таблиці;.
        /// </summary>
        internal static string HelpText7 {
            get {
                return ResourceManager.GetString("HelpText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. Щоб побачити графік по даній головоломці написніть пункт меню Графік;.
        /// </summary>
        internal static string HelpText8 {
            get {
                return ResourceManager.GetString("HelpText8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8. Щоб не бачити секундоміра під час збірки зніміть галочку в &quot;Показати час&quot;;.
        /// </summary>
        internal static string HelpText9 {
            get {
                return ResourceManager.GetString("HelpText9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НЕПРАВИЛЬНА ДАТА ЗБІРКИ.
        /// </summary>
        internal static string incorrectDate {
            get {
                return ResourceManager.GetString("incorrectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НЕПРАВИЛЬНИЙ СКРАМБЛ.
        /// </summary>
        internal static string incorrectScramble {
            get {
                return ResourceManager.GetString("incorrectScramble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , СКРАМБЛ.
        /// </summary>
        internal static string incorrectScramblePlus {
            get {
                return ResourceManager.GetString("incorrectScramblePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НЕПРАВИЛЬНИЙ ЧАС ЗБІРКИ.
        /// </summary>
        internal static string incorrectTime {
            get {
                return ResourceManager.GetString("incorrectTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , ЧАС ЗБІРКИ.
        /// </summary>
        internal static string incorrectTimePlus {
            get {
                return ResourceManager.GetString("incorrectTimePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мова:.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ост.:.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новий скрамбл.
        /// </summary>
        internal static string NewScramble {
            get {
                return ResourceManager.GetString("NewScramble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибрана головоломка:.
        /// </summary>
        internal static string PuzzleType {
            get {
                return ResourceManager.GetString("PuzzleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрамбл:.
        /// </summary>
        internal static string Scramble {
            get {
                return ResourceManager.GetString("Scramble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показати час.
        /// </summary>
        internal static string ShowTime {
            get {
                return ResourceManager.GetString("ShowTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата збірки:.
        /// </summary>
        internal static string SolutionDate {
            get {
                return ResourceManager.GetString("SolutionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Час збірки:.
        /// </summary>
        internal static string SolutionTime {
            get {
                return ResourceManager.GetString("SolutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приклад: години:хвилини:секунди.мілісекунди(тільки перші дві цифри, наприклад, якщо 63 мілісекунди, тоді напишіть 0.06, 727 мілісекунди тоді 0.72).
        /// </summary>
        internal static string SolutionTimeTextBoxToolTipText {
            get {
                return ResourceManager.GetString("SolutionTimeTextBoxToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таблиця.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема:.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розгортка.
        /// </summary>
        internal static string Unfold {
            get {
                return ResourceManager.GetString("Unfold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оновити.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Немає записів! Неможливо побудувати графік!.
        /// </summary>
        internal static string ZeroItemsCantDrawChart {
            get {
                return ResourceManager.GetString("ZeroItemsCantDrawChart", resourceCulture);
            }
        }
    }
}
